name: Build and Test Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker Image
      run: docker build -t devops-mini-test .
    
    - name: Test Container
      run: docker run -d -p 5000:5000 --name test-container devops-mini-test && sleep 5 && curl -f http://localhost:5000 || exit 1
